
#List of diet effects
#max health for balanced diet
[[effects]]
	[[effects.attributes]]
		amount = -3.5
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.1
		match = "every"
		above = 0.0
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -3.0
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.2
		match = "every"
		above = 0.1
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -2.5
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.3
		match = "every"
		above = 0.2
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -2.0
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.4
		match = "every"
		above = 0.3
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -1.5
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.5
		match = "every"
		above = 0.4
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -1.0
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.6
		match = "every"
		above = 0.5
		groups = ["proteins", "vegetables", "grains"]

[[effects]]
	[[effects.attributes]]
		amount = -0.5
		name = "minecraft:generic.max_health"
		operation = "add"
	[[effects.conditions]]
		below = 0.7
		match = "every"
		above = 0.6
		groups = ["proteins", "vegetables", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = 1.0
		name = "minecraft:generic.max_health"
		operation = "add"

	[[effects.conditions]]
		below = 0.9
		match = "every"
		above = 0.8
		groups = ["proteins", "vegetables", "plant_oil", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = 2.0
		name = "minecraft:generic.max_health"
		operation = "add"

	[[effects.conditions]]
		below = 1.0
		match = "every"
		above = 0.9
		groups = ["proteins", "vegetables", "plant_oil", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = 2.0
		name = "minecraft:generic.attack_damage"
		operation = "add"

	[[effects.attributes]]
		amount = 0.1
		name = "minecraft:generic.attack_speed"
		operation = "multiply_total"

	[[effects.conditions]]
		below = 1.0
		match = "all"
		above = 0.8
		groups = ["proteins", "vegetables", "plant_oil", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = -2.0
		name = "minecraft:generic.attack_damage"
		operation = "add"

	[[effects.attributes]]
		amount = -0.1
		name = "minecraft:generic.attack_speed"
		operation = "multiply_total"

	[[effects.attributes]]
		amount = -0.2
		name = "minecraft:generic.movement_speed"
		operation = "multiply_base"

	[[effects.conditions]]
		below = 0.2
		match = "any"
		above = 0.0
		groups = ["proteins", "vegetables", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = 0.1
		name = "minecraft:generic.knockback_resistance"
		operation = "add"

	[[effects.attributes]]
		amount = 1.0
		name = "minecraft:generic.armor_toughness"
		operation = "add"

	[[effects.conditions]]
		below = 1.0
		match = "every"
		above = 0.8
		groups = ["proteins", "vegetables", "plant_oil", "grains"]

[[effects]]

	[[effects.attributes]]
		amount = -0.1
		name = "minecraft:generic.knockback_resistance"
		operation = "add"

	[[effects.attributes]]
		amount = -1.0
		name = "minecraft:generic.armor_toughness"
		operation = "add"

	[[effects.conditions]]
		below = 0.2
		match = "every"
		above = 0.0
		groups = ["proteins", "vegetables", "grains"]
#Negative effects for lackage
[[effects]]

	[[effects.attributes]]
		amount = -0.1
		name = "minecraft:generic.movement_speed"
		operation = "multiply_base"

	[[effects.status_effects]]
		name = "minecraft:weakness"
		power = 3
	[[effects.status_effects]]
		name = "frostedheart:anemia"
		power = 0
	[[effects.conditions]]
		below = 1.0
		match = "all"
		above = 0.8
		groups = ["vitamin"]
[[effects]]
	[[effects.status_effects]]
		name = "minecraft:hunger"
		power = 1
	[[effects.conditions]]
		below = 0.1
		match = "all"
		above = 0.0
		groups = ["grains"]
[[effects]]
	[[effects.status_effects]]
		name = "frostedheart:scurvy"
		power = 1

	[[effects.conditions]]
		below = 0.1
		match = "all"
		above = 0.0
		groups = ["vegetables"]
[[effects]]
	[[effects.status_effects]]
		name = "frostedheart:scurvy"
		power = 0

	[[effects.conditions]]
		below = 0.2
		match = "all"
		above = 0.1
		groups = ["vegetables"]
[[effects]]
	[[effects.status_effects]]
		name = "frostedheart:anemia"
		power = 1

	[[effects.conditions]]
		below = 0.1
		match = "all"
		above = 0.0
		groups = ["proteins"]
[[effects]]
	[[effects.status_effects]]
		name = "frostedheart:anemia"
		power = 0

	[[effects.conditions]]
		below = 0.2
		match = "all"
		above = 0.1
		groups = ["proteins"]
[[effects]]
	[[effects.status_effects]]
		name = "frostedheart:nyctalopia"
		power = 0

	[[effects.conditions]]
		below = 0.2
		match = "any"
		above = 0.0
		groups = ["vegetables","proteins"]
[[effects]]

	[[effects.attributes]]
		amount = -0.2
		name = "minecraft:generic.movement_speed"
		operation = "multiply_base"
	
	[[effects.attributes]]
		amount = 0.0
		name = "diet:natural_regeneration"
		operation = "multiply_base"

	[[effects.status_effects]]
		name = "minecraft:hunger"
		power = 3

	[[effects.conditions]]
		below = 1.0
		match = "all"
		above = 0.8
		groups = ["sugars"]

